#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${AUTH_DATABASE_USER} WITH PASSWORD '${AUTH_DATABASE_PASSWORD}';
    CREATE DATABASE ${AUTH_DATABASE_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${AUTH_DATABASE_NAME} TO ${AUTH_DATABASE_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${SCRAPER_DATABASE_USER} WITH PASSWORD '${SCRAPER_DATABASE_PASSWORD}';
    CREATE DATABASE ${SCRAPER_DATABASE_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${SCRAPER_DATABASE_NAME} TO ${SCRAPER_DATABASE_USER};
EOSQL
