version: 2.1

jobs:
  build-deploy-all:
    machine: true
    working_directory: ~/demo

    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:login
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - run:
          name: Build Docker image - Keycloak
          command: |
            cd ./auth-server
            docker build --rm=false -t majidhajric/demo-authentication-server:$CIRCLE_SHA1 .
            docker push majidhajric/demo-authentication-server:$CIRCLE_SHA1
            heroku container:push -a $HEROKU_APP_NAME_AUTHENTICATION_SERVER web
            heroku container:release -a $HEROKU_APP_NAME_AUTHENTICATION_SERVER web

      - run:
          name: Build Docker image - front-end
          command: |
            cd ./web-ui
            docker build --rm=false --build-arg CONFIGURATION=heroku -t majidhajric/scraper-web-ui:$CIRCLE_SHA1 .
            docker push majidhajric/scraper-web-ui:$CIRCLE_SHA1
            heroku container:push -a $HEROKU_APP_NAME_FRONT_END web
            heroku container:release -a $HEROKU_APP_NAME_FRONT_END web

      - run:
          name: Build Docker image - back-end
          command: |
            cd ./scraper
            docker build --rm=false -t majidhajric/scraper:$CIRCLE_SHA1 .
            docker push majidhajric/scraper:$CIRCLE_SHA1
            heroku container:push -a $HEROKU_APP_NAME_BACK_END web
            heroku container:release -a $HEROKU_APP_NAME_BACK_END web

workflows:
  build:
    jobs:
      - build-deploy-all
